# Generated by Django 4.2.16 on 2024-09-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candlestickdata',
            name='close',
        ),
        migrations.RemoveField(
            model_name='candlestickdata',
            name='high',
        ),
        migrations.RemoveField(
            model_name='candlestickdata',
            name='low',
        ),
        migrations.RemoveField(
            model_name='candlestickdata',
            name='open',
        ),
        migrations.RemoveField(
            model_name='candlestickdata',
            name='x',
        ),
        migrations.AddField(
            model_name='candlestickdata',
            name='data',
            field=models.JSONField(default={'data': [{'close': 35, 'high': 40, 'low': 25, 'open': 30, 'x': '2023-01-01'}, {'close': 40, 'high': 45, 'low': 30, 'open': 35, 'x': '2023-01-02'}]}),
        ),
        migrations.AlterField(
            model_name='barchartdata',
            name='data',
            field=models.JSONField(default={'data': [100, 150, 200], 'labels': ['Product A', 'Product B', 'Product C']}),
        ),
        migrations.AlterField(
            model_name='linechartdata',
            name='data',
            field=models.JSONField(default={'data': [10, 20, 30, 40], 'labels': ['Jan', 'Feb', 'Mar', 'Apr']}),
        ),
        migrations.AlterField(
            model_name='piechartdata',
            name='data',
            field=models.JSONField(default={'data': [300, 50, 100], 'labels': ['Red', 'Blue', 'Yellow']}),
        ),
    ]
